Dark mode
memlernado/J-M-Shower pull request #6
Opened 2023-10-03 17:25 UTC by magodi9

## Description

 Create dark mode functionality and fix error with icon changing

   Add icons and styles to be able to change to dark mode
## Screenshots
![image](https://github.com/memlernado/J-M-Shower/assets/45546415/c527e1d5-3026-4e13-97ec-c3ee15141ad6)

![image](https://github.com/memlernado/J-M-Shower/assets/45546415/29cae9cf-8863-4b51-b570-83b4b322861f)
![image](https://github.com/memlernado/J-M-Shower/assets/45546415/1daebe8a-86f0-4850-8d73-4f1facc175d6)

2023-10-03 19:47 UTC, sagodi97 commented on src/components/Login.tsx
> +        setTimeout(() => {
Para evitar errores, te recomendaría usar `clearTimeout` en `.finally`

2023-10-03 19:50 UTC, sagodi97 commented on src/components/item.tsx
> +                if (t.name) setInput(t.name);
Esto podría pasar cuando inicializas el state e.g.   const [input, setInput] = useState(() => t.name ?? "");

2023-10-03 19:52 UTC, sagodi97 commented on src/components/items.tsx
> +  };
Nice!

2023-10-03 20:10 UTC, sagodi97 commented on src/components/items.tsx
> +        localUpdate();
¿Si hay un error llamas el mismo método que llamaste antes?

2023-10-03 20:11 UTC, sagodi97 commented on tsconfig.json
> +    "types": ["vite-plugin-svgr/client"]
🚀

2023-10-03 20:12 UTC, sagodi97 commented on src/components/items.tsx
> +          ></Item>
Puedes cerrarlo solo si el componente no espera `children`
```suggestion
          />
```

2023-10-03 20:17 UTC, sagodi97 requested changes
Súper! Te dejé un par de comentarios menores y uno no tan menor (en `updateItem`). Aparte de eso, todo se ve muy bien. Lo único es que no vi Dark Mode en ninguna parte, así que porfa actualiza la PR para reflejar lo que realmente se hizo aquí ;)

2023-10-04 16:36 UTC, magodi9 commented on tsconfig.json
> +    "types": ["vite-plugin-svgr/client"]
No entiendo, cual es el error?

2023-10-04 17:57 UTC, closed without merging